import { GoogleGenerativeAI } from '@google/generative-ai';

export const analyzePrescription = async (req, res) => {
  try {
    const { diagnosis, symptoms, prescriptions } = req.body;
    if (!diagnosis) {
      return res.status(400).json({ message: 'Diagnosis description is required.' });
    }

    const apiKey = process.env.GEMINI_API_KEY;

    // Check if key is configured
    if (!apiKey || apiKey.includes('your_') || apiKey.includes('placeholder')) {
      console.log('Gemini API key not found. Providing mock clinical advice fallback...');
      const mockAdvice = {
        recommendations: `1. Ensure proper rest and hydration (at least 2-3 liters of water daily).\n2. Monitor vital signs regularly (especially temperature and BP).\n3. Avoid strenuous physical activity until recovery.`,
        warnings: `No drug interactions found for: ${
          prescriptions?.length > 0 ? prescriptions.map((p) => p.drugName).join(', ') : 'None'
        }. Verify that the patient has no historical allergies to these substances.`,
        carePlan: `Standard clinical support plan for "${diagnosis}". Scheduled follow-up consultation in 5 days if symptoms persist.`
      };
      return res.status(200).json(mockAdvice);
    }

    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });

    const prompt = `
      You are a clinical assistant AI. Review this patient case and output a JSON response.
      Diagnosis: "${diagnosis}"
      Symptoms: "${symptoms || 'Not logged'}"
      Prescriptions: ${JSON.stringify(prescriptions || [])}

      Provide your review in this exact JSON schema format (do NOT wrap in markdown fences like \`\`\`json, just return the raw text parseable by JSON.parse):
      {
        "recommendations": "Detailed clinical recommendations and lifestyle suggestions.",
        "warnings": "Drug-to-drug interactions warnings, allergy alerts, or cautions.",
        "carePlan": "Custom patient wellness care plan."
      }
    `;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();

    // Strip markdown JSON wrappers if generated by model
    const cleanText = text.replace(/```json/i, '').replace(/```/g, '').trim();
    const parsed = JSON.parse(cleanText);

    res.status(200).json(parsed);
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: 'AI Assistant failed: ' + error.message });
  }
};
